# Generated by Django 3.1.7 on 2021-04-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210417_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interface',
        ),
    ]
